### ISSUE TITLE
Add a new option to choice where to show the pagantis widget

### ISSUE THREAD

**Issue by Maofree** [pagantis/prestashop#82]
Hi
I'm a coder and I'm installing this plugin on some prestashop 1.7.6 sites managed by me
one shopkeeper say me that the product pages are slower to load and he prefer to show the simulator in the cart summary

can you add an option to decide if show it on the product pages and another one to decide to show it in the cart summary?

in the payments selection (on confirmation page) is mandatory

there are some hooks like displayReassurance
and use
$page_name = Dispatcher::getInstance()->getController();
to load the scripts only in restricted pages

another important thing is avoid to load the script in extra pages

![Performance - SEO Zoom 30-6-2020 17-47-27](https://user-images.githubusercontent.com/653230/86156730-b50dcd80-bb06-11ea-8644-ba59d0016b3b.jpg)

from here you can see the performance about the site after installed this module

thanks

**Comment by rmarinleal** [comment]
Hi,

Sorry to hear that.

We've made several tests to improve and increase the funnels and conversion rates with many merchants and the optimum is to allow the customer to know Pagantis method and the prices before he/she decides to add the product to cart, so the product page (and banners in the home screen) are the best places.

So that we don't allow our module to put the installments simulator on the cart page.

Regards
