### ISSUE TITLE
Add the style selection

### ISSUE THREAD

**Issue by Maofree** [pagantis/prestashop#83]
Hi
is it possible to add an option to decide the style of widget?

![code (6)](https://user-images.githubusercontent.com/653230/86149551-64917280-bafc-11ea-9ebd-7a46d618f457.jpg)

I know that there are two type of style and the other is much better

thanks

**Comment by tmeliotpg** [comment]
The simulator you are referring to is a SIMPLE  simulator, we made the conscious decision to  remove this simulator type our catalog.
The reason is that we have been able to verify that the new simulator converts better in sales than the previous one.
This practice finally achieves that we have more access to our payment method, and therefore more sales.
