### ISSUE TITLE
Display min amount does not work

### ISSUE THREAD

**Issue by Maofree** [pagantis/prestashop#95]
hi
right now I've upgraded the module from 8.5.1 to 8.6.7 and seems that the option "display min amount" does not work

from here you can see that the regular simulator is shown
https://www.solariabio.it/integratori-alimentari-naturali-in-capsule/526-viridian-vitamin-d3-400-ui-30-capsule.html

in ps_pagantis_config I can see the value "50" set in the past version

can you check please?
thanks

![1](https://user-images.githubusercontent.com/653230/91747556-b28b2b00-ebbe-11ea-9f48-39e6256fc8f6.png)
![2](https://user-images.githubusercontent.com/653230/91747564-b454ee80-ebbe-11ea-9cae-c0122b1d8e09.png)

**Comment by Maofree** [comment]
hi
I've tested it on 7 sites and they have the same errors, pagantis is shown also under "display min amount" value

**Comment by bruno-rc** [comment]
I confirm that it doesn't work for me either

**Comment by tmeliotpg** [comment]
Please email integrations@pagantis.com with the URL of store and this issue as a reference.

Regards.

**Comment by Maofree** [comment]
hi
I've sent to them an email with the access to the site

**Comment by pagantis-integrations** [comment]
Hi!

Thanks for your feedback!!

Your problem is in the way you're changing the extra config value.

On 8.6.x versions, we change this way to a json encoded value on a DB field. If you search for a config named "PAGANTIS" You will find a json value, decoding it, you wil find a min_amount to set. This is the correct value.

Also you can use our controller tool to do it easier callig this url (you must change the XXXX by your secret key):
If you've configured the 4x options:
https://yourchop.com/index.php?fc=module&module=pagantis&controller=config&secret=XXXXXXXXXXX&product=P4X

If you've configured the 4x options:
https://yourchop.com/index.php?fc=module&module=pagantis&controller=config&secret=XXXXXXXXXXX&product=PAGANTIS

A GET request shows you the values and a POST request sending the FORM FIELD parameter (key and value) will change the value of the config (you can do it with postman, insomnia or a similar request tool).

Best Regards.

**Comment by rmarinleal** [comment]
Hi!

Thanks for your feedback!!

Your problem is in the way you're changing the extra config value.

On 8.6.x versions, we change this way to a json encoded value on a DB field. If you search for a config named "PAGANTIS" You will find a json value, decoding it, you wil find a min_amount to set. This is the correct value.

Also you can use our controller tool it is easier. By calling this URL (you must change the XXXX by your secret key located in your backoffice):
If you've configured the 4x options:

`https://yourdomain.com/index.php?fc=module&module=pagantis&controller=config&secret=XXXXXXXXXXX&product=P4X`

If you've configured the 12x options:

`https://yourdomain.com/index.php?fc=module&module=pagantis&controller=config&secret=XXXXXXXXXXX&product=PAGANTIS`

A GET request shows you the values and a POST request sending the FORM FIELD parameter (key and value) will change the value of the config (you can do it with postman, insomnia or a similar request tool).

Best Regards.

**Comment by Maofree** [comment]
hi rmarinleal
can you explain me better this part?

On 8.6.x versions, we change this way to a json encoded value on a DB field. If you search for a config named "PAGANTIS" You will find a json value, decoding it, you wil find a min_amount to set. This is the correct value.

to change some options should be simpler
I manage 25 sites, I don't have time to waste setting a parameter

from the 12x url I can see all parameters and that value to zero.
tell me step by step without use extra tool like postman ... to change it to ex. 50

it didn't make sense to me to put settings in a database table now even less

at this moment I still don't understand where to change these parameters, but wasn't it better to make a variable in ps_configuration using serialize function where you put all the options without using tables or complex things?

and i don't even want to decode a json value, it must be easy to change a parameter. When you make a program you should put yourself in others' shoes
